# Generated by Django 5.2.7 on 2025-10-19 13:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('vagas', '0003_alter_certificacao_nome_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FonteBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_site', models.CharField(max_length=100)),
                ('url_perfil', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Candidato',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_candidato', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField(blank=True, null=True)),
                ('resumo_profissional', models.TextField(blank=True, null=True)),
                ('compatibilidade', models.FloatField(default=0.0)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidatos', to='vagas.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoCertificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificacoes', to='candidatos.candidato')),
                ('certificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.certificacao')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diplomas', to='candidatos.candidato')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.diploma')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emails', to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='empresas', to='candidatos.candidato')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoHabilidadeInterpessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_interpessoais', to='candidatos.candidato')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.habilidadeinterpessoal')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoHabilidadeTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='habilidades_tecnicas', to='candidatos.candidato')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.habilidadetecnica')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idiomas', to='candidatos.candidato')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.idioma')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='localizacoes', to='candidatos.candidato')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.localizacao')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoTelefone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefone', models.CharField(max_length=20)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telefones', to='candidatos.candidato')),
            ],
        ),
        migrations.CreateModel(
            name='CandidatoFonteBusca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_coleta', models.DateTimeField(auto_now_add=True)),
                ('candidato', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fontes_busca', to='candidatos.candidato')),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='candidatos.fontebusca')),
            ],
            options={
                'unique_together': {('candidato', 'fonte')},
            },
        ),
    ]
