# Generated by Django 5.2.7 on 2025-10-07 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Diploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('Bacharelado', 'Bacharelado'), ('Licenciatura', 'Licenciatura'), ('Tecnólogo', 'Tecnólogo'), ('Mestrado', 'Mestrado'), ('Doutorado', 'Doutorado')], max_length=20)),
                ('area', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('nivel', models.CharField(choices=[('Júnior', 'Júnior'), ('Pleno', 'Pleno'), ('Sênior', 'Sênior')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeInterpessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='HabilidadeTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Idioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('nivel', models.CharField(choices=[('Básico', 'Básico'), ('Intermediário', 'Intermediário'), ('Avançado', 'Avançado'), ('Fluente', 'Fluente')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Localizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pais', models.CharField(blank=True, max_length=50, null=True)),
                ('estado', models.CharField(blank=True, max_length=50, null=True)),
                ('cidade', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cargo', models.CharField(max_length=100)),
                ('modalidade', models.CharField(choices=[('Presencial', 'Presencial'), ('À distância', 'À distância'), ('Híbrido', 'Híbrido')], max_length=20)),
                ('tipo_contrato', models.CharField(choices=[('Prazo indeterminado', 'Prazo indeterminado'), ('Prazo determinado', 'Prazo determinado'), ('Experiência', 'Experiência'), ('Temporário', 'Temporário'), ('Intermitente', 'Intermitente'), ('Estágio', 'Estágio')], max_length=30)),
                ('quantidade', models.PositiveIntegerField(default=1)),
                ('prioridade', models.CharField(choices=[('Baixa', 'Baixa'), ('Média', 'Média'), ('Alta', 'Alta')], max_length=10)),
                ('observacao', models.TextField(blank=True, null=True)),
                ('data_solicitacao', models.DateField(auto_now_add=True)),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_solicitadas', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DecisaoVaga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Aprovada', 'Aprovada'), ('Rejeitada', 'Rejeitada')], max_length=10)),
                ('justificativa', models.TextField(blank=True, null=True)),
                ('data_decisao', models.DateTimeField(auto_now_add=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vagas_analisadas', to=settings.AUTH_USER_MODEL)),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisoes', to='vagas.vaga')),
            ],
        ),
        migrations.CreateModel(
            name='VagaCertificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('certificacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.certificacao')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'certificacao')},
            },
        ),
        migrations.CreateModel(
            name='VagaDiploma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diploma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.diploma')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'diploma')},
            },
        ),
        migrations.CreateModel(
            name='VagaEmpresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.empresa')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'empresa')},
            },
        ),
        migrations.CreateModel(
            name='VagaHabilidadeInterpessoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.habilidadeinterpessoal')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'habilidade')},
            },
        ),
        migrations.CreateModel(
            name='VagaHabilidadeTecnica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('habilidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.habilidadetecnica')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'habilidade')},
            },
        ),
        migrations.CreateModel(
            name='VagaIdioma',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idioma', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.idioma')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'idioma')},
            },
        ),
        migrations.CreateModel(
            name='VagaLocalizacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localizacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.localizacao')),
                ('vaga', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vagas.vaga')),
            ],
            options={
                'unique_together': {('vaga', 'localizacao')},
            },
        ),
    ]
