# Generated by Django 5.2.7 on 2025-10-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vagas', '0002_vaga_status_alter_decisaovaga_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificacao',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='habilidadeinterpessoal',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='habilidadetecnica',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
